// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BASS_DX8_PARAMEQ {
  final double fCenter;
  final double fBandwidth;
  final double fGain;

  const BASS_DX8_PARAMEQ({
    required this.fCenter,
    required this.fBandwidth,
    required this.fGain,
  });

  static Future<BASS_DX8_PARAMEQ> default_() =>
      RustLib.instance.api.crateApiBassBassFuncBassDx8ParameqDefault();

  @override
  int get hashCode => fCenter.hashCode ^ fBandwidth.hashCode ^ fGain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BASS_DX8_PARAMEQ &&
          runtimeType == other.runtimeType &&
          fCenter == other.fCenter &&
          fBandwidth == other.fBandwidth &&
          fGain == other.fGain;
}
