// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dummy_wasapi_proc`

class BASS_WASAPI_INFO {
  final int initflags;
  final int freq;
  final int chans;
  final int format;
  final int buflen;
  final double volmax;
  final double volmin;
  final double volstep;

  const BASS_WASAPI_INFO({
    required this.initflags,
    required this.freq,
    required this.chans,
    required this.format,
    required this.buflen,
    required this.volmax,
    required this.volmin,
    required this.volstep,
  });

  static Future<BASS_WASAPI_INFO> default_() =>
      RustLib.instance.api.crateApiBassBasswasapiFuncBassWasapiInfoDefault();

  @override
  int get hashCode =>
      initflags.hashCode ^
      freq.hashCode ^
      chans.hashCode ^
      format.hashCode ^
      buflen.hashCode ^
      volmax.hashCode ^
      volmin.hashCode ^
      volstep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BASS_WASAPI_INFO &&
          runtimeType == other.runtimeType &&
          initflags == other.initflags &&
          freq == other.freq &&
          chans == other.chans &&
          format == other.format &&
          buflen == other.buflen &&
          volmax == other.volmax &&
          volmin == other.volmin &&
          volstep == other.volstep;
}
