// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initSmtc() => RustLib.instance.api.crateApiSmtcInitSmtc();

Future<void> smtcUpdateState({required int state}) =>
    RustLib.instance.api.crateApiSmtcSmtcUpdateState(state: state);

Future<void> smtcUpdateMetadata({
  required String title,
  required String artist,
  required String album,
  required List<int> coverSrc,
}) => RustLib.instance.api.crateApiSmtcSmtcUpdateMetadata(
  title: title,
  artist: artist,
  album: album,
  coverSrc: coverSrc,
);

Stream<int> smtcControlEvents() =>
    RustLib.instance.api.crateApiSmtcSmtcControlEvents();

Future<void> smtcClear() => RustLib.instance.api.crateApiSmtcSmtcClear();
